import os

godot_cpp_dir = os.environ.get("GODOT_CPP_DIR", os.path.join(os.getcwd(), "godot-cpp"))
env = SConscript(os.path.join(godot_cpp_dir, "SConstruct"))

env.Append(CPPPATH=[
    "extension/",
    os.path.join(godot_cpp_dir, "include"),
    os.path.join(godot_cpp_dir, "gen", "include"),
])

sources = Glob("extension/*.cpp")
if env["platform"] == "windows":
    env["AS"] = env.get("CC", "cc")
    env["ASCOM"] = "$AS -c $SOURCES -o $TARGET"
asm_sources = Glob("extension/*.S")
sources += env.Object(asm_sources)

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "build/coopnativepatch/libcoopnativepatch.{}.{}.framework/libcoopnativepatch.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "build/coopnativepatch/libcoopnativepatch{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
